apiVersion: v1
data:
  datasource.yaml: |-
    apiVersion: 1
    datasources:
    - name: "Prometheus"
      type: prometheus
      uid: prometheus
      url: http://monitoring-kube-prometheus-prometheus.monitoring:9090/
      access: proxy
      isDefault: true
      jsonData:
        httpMethod: POST
        timeInterval: 30s
    - name: "Alertmanager"
      type: alertmanager
      uid: alertmanager
      url: http://monitoring-kube-prometheus-alertmanager.monitoring:9093/
      access: proxy
      jsonData:
        handleGrafanaManagedAlerts: false
        implementation: prometheus
kind: ConfigMap
metadata:
  annotations:
    meta.helm.sh/release-name: monitoring
    meta.helm.sh/release-namespace: monitoring
  creationTimestamp: "2026-05-19T14:31:42Z"
  labels:
    app: kube-prometheus-stack-grafana
    app.kubernetes.io/instance: monitoring
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/part-of: kube-prometheus-stack
    app.kubernetes.io/version: 85.1.3
    chart: kube-prometheus-stack-85.1.3
    grafana_datasource: "1"
    heritage: Helm
    release: monitoring
  name: monitoring-kube-prometheus-grafana-datasource
  namespace: monitoring
  resourceVersion: "1633"
  uid: 54a490ba-c72d-4177-83a5-452fc78f2abc
